changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      commit_patterns:
        - "^(?<type>\\w+(?:\\((?<scope>[^)]+)\\))?!:\\s*)"
      semver: major
    - title: New Features
      commit_patterns:
        - "^(?<type>feat(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
      semver: minor
    - title: Bug Fixes
      commit_patterns:
        - "^(?<type>fix(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
        - '^Revert "'
      semver: patch
    - title: Schema Updates
      commit_patterns:
        - "^Generated"
      semver: minor
    - title: Internal Changes
      commit_patterns:
        - "^(?<type>(?:build|refactor|meta|chore|ci|ref|perf|docs?)(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
      semver: patch
