minVersion: "2.21.1"
changelog:
  policy: auto
artifactProvider:
  name: github
  config:
    artifacts:
      build.yml:
        - build-artifacts
preReleaseCommand: node --experimental-strip-types scripts/pre-release.ts
targets:
  - name: npm
  - name: github
