/**
 * Bind the generated operations to one transport without duplicating request
 * logic. Keep each operation's generics, required arguments, and documentation.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sdkPath = join(root, "src", "sdk.gen.ts");
const source = ts.createSourceFile(
  sdkPath,
  readFileSync(sdkPath, "utf8"),
  ts.ScriptTarget.Latest,
  true,
);

const methods = [];
for (const statement of source.statements) {
  if (
    !ts.isVariableStatement(statement) ||
    !statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)
  ) continue;

  for (const declaration of statement.declarationList.declarations) {
    const fn = declaration.initializer;
    if (
      !ts.isIdentifier(declaration.name) ||
      !fn || !ts.isArrowFunction(fn) ||
      fn.parameters.length !== 1 ||
      fn.parameters[0].dotDotDotToken ||
      fn.parameters[0].initializer
    ) {
      throw new Error(`Unsupported SDK operation: ${declaration.name.getText(source)}`);
    }

    const name = declaration.name.text;
    if (name === "client") throw new Error("SDK operation conflicts with the client property");

    const generics = fn.typeParameters?.length
      ? `<${fn.typeParameters.map((parameter) => parameter.getText(source)).join(", ")}>`
      : "";
    const typeArguments = fn.typeParameters?.length
      ? `<${fn.typeParameters.map((parameter) => parameter.name.text).join(", ")}>`
      : "";
    const operation = `sdk.${name}${typeArguments}`;
    const optional = fn.parameters[0].questionToken ? "?" : "";
    for (const doc of statement.jsDoc ?? []) {
      methods.push(...doc.getText(source).split("\n").map((line) => `    ${line}`));
    }
    methods.push(
      `    ${name}: ${generics}(`,
      `      options${optional}: Omit<NonNullable<Parameters<typeof ${operation}>[0]>, 'client'>,`,
      `    ) => ${operation}({ ...options, client }),`,
    );
  }
}

if (methods.length === 0) throw new Error("No SDK operations found");

writeFileSync(join(root, "src", "sentry-client.gen.ts"), [
  "// This file is auto-generated by scripts/generate-client.mjs",
  "// Do not edit directly. Re-run `bun run build` to regenerate.",
  "",
  "import { createClient, type Config } from './client';",
  "import * as sdk from './sdk.gen';",
  "",
  "/**",
  " * Create an isolated Sentry client with bound, typed API operations.",
  " * Use `client` for transport configuration, interceptors, and standalone helpers.",
  " * Each method keeps the standalone operation's result and request options.",
  " */",
  "export function createSentryClient(config: Config = {}) {",
  "  const client = createClient(config);",
  "  return {",
  "    client,",
  ...methods,
  "  } as const;",
  "}",
  "",
  "export type SentryClient = ReturnType<typeof createSentryClient>;",
  "",
].join("\n"));
