name: Cascade to sentry-docs
on:
  push:
    branches:
      - "main"
  workflow_dispatch:  # temp for testing, remove if you like
jobs:
  cascade-to-sentry-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Cascade to sentry-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        run: gh workflow run "Bump API Schema SHA" -R getsentry/sentry-docs
