name: Cascade to sentry-docs
on:
  push:
    branches:
      - "main"
  workflow_dispatch:  # temp for testing, remove if you like
jobs:
  cascade-to-sentry-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Get auth token
        id: token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.SENTRY_API_SCHEMA_UPDATER_APP_CLIENT_ID }}
          private-key: ${{ secrets.SENTRY_API_SCHEMA_UPDATER_PRIVATE_KEY }}
          repositories: sentry-docs
      - name: Cascade to sentry-docs
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: gh workflow run "Bump API Schema SHA" -R getsentry/sentry-docs
