name: sentry-docs
on:
  push:
    branches:
      - "main"

jobs:
  bump:
    runs-on: ubuntu-18.04
    steps:
      # Notify sentry-docs
      - name: Dispatch to sentry-docs
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_SENTRY_BOT_PAT }}
          script: |
            github.actions.createWorkflowDispatch({
              owner: 'getsentry',
              repo: 'sentry-docs',
              workflow_id: 'bump-openapi.yml',
              ref: 'master',
              inputs: {
                'sentry-api-schema-sha': '${{ github.sha }}',
              }
            })
