name: sentry-docs
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  trigger_docs_release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger new docs release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        run: gh workflow run release -R getsentry/sentry-docs
