name: sentry-docs
on:
  push:
    branches:
      - "main"

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger new docs deploy
        run: curl -X POST "${{ secrets.DOCS_DEPLOY_URL }}"
          
